name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: E1.1
      id: e1-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E1.1
        setup-command: g++ hallo.cc -o hallo
        command: "./hallo"
        input: ''
        expected-output: llo
        comparison-method: contains
        timeout: 5
        max-score: 1
    - name: E1.2
      id: e1-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E1.2
        setup-command: g++ -o summieren summieren.cc; ./summieren
        command: cat datensumme.txt
        input: ''
        expected-output: |-
          4
          2
          3
          1
          3
          2
          2
          1
          5
          0
          4
          4
          3
          2
          2
          3
          2
          2
          4
          4
          5
          3
          4
          3
          3
          2
          6
          0
          2
          6
          5
          4
          2
          2
          1
          2
          4
          2
          4
          1
          3
          7
          2
          4
          0
          2
          1
          3
          3
          4
          3
          6
          5
          5
          2
          7
          4
          0
          2
          3
          0
          3
          6
          8
          4
          4
          0
          4
          4
          2
          2
          4
          4
          4
          3
          3
          3
          4
          2
          0
          8
          3
          2
          4
          5
          4
          1
          3
          3
          3
          3
          3
          4
          4
          5
          2
          5
          3
          3
          2
          6
          6
          4
          3
          1
          7
          2
          5
          1
          2
          1
          3
          2
          2
          2
          3
          2
          4
          3
          3
          1
          3
          4
          1
          2
          3
          2
          0
          3
          2
          4
          2
          3
          5
          3
          2
          4
          2
          3
          3
          1
          2
          2
          4
          3
          4
          5
          4
          1
          1
          3
          5
          2
          4
          1
          5
          4
          3
          1
          1
          4
          3
          4
          6
          2
          6
          3
          3
          4
          5
          4
          3
          2
          4
          2
          1
          2
          2
          3
          4
          6
          6
          0
          3
          2
          6
          4
          4
          3
          5
          0
          3
          4
          3
          2
          2
          2
          0
          2
          1
          3
          6
          3
          3
          3
          5
          2
          3
          4
          2
          5
          3
          1
          6
          6
          2
          6
          6
          4
          0
          3
          1
          3
          5
          3
          2
          1
          2
          4
          7
          5
          4
          1
          6
        comparison-method: exact
        timeout: 5
        max-score: 10
    - name: E2.1
      id: e2-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E2.1
        setup-command: g++ -o stichprobe stichprobe.cc
        command: "./stichprobe"
        input: ''
        expected-output: '1.65365'
        comparison-method: contains
        timeout: 5
        max-score: 100
    - name: E2.2a
      id: e2-2a
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E2.2a
        setup-command: g++ stichprobe2.cc -o stichprobe2; ./stichprobe2
        command: 'cat mittelwerte.txt; cat varianzen.txt '
        input: ''
        expected-output: |-
          2.55556
          2.44444
          3.77778
          2.66667
          3
          3.55556
          3
          3.55556
          3.44444
          3.11111
          3.55556
          4
          2
          2.66667
          2.66667
          2.55556
          3.11111
          2.88889
          4.11111
          2.55556
          3.77778
          2.33333
          3.11111
          3.55556
          3.44444
          3.55556
          1.58025
          1.35802
          1.28395
          3.33333
          3.77778
          2.24691
          5.11111
          4.24691
          4.02469
          1.20988
          0.91358
          4
          0.444444
          1.11111
          1.77778
          0.91358
          2.09877
          2.09877
          1.65432
          0.91358
          3.7284
          2.44444
          2.09877
          2.91358
          3.80247
          4.24691
        comparison-method: exact
        timeout: 5
        max-score: 500
    - name: E2.2b
      id: e2-2b
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: E2.2b
        setup-command: g++ stichprobe2.cc -o stichprobe2
        command: "./stichprobe2"
        input: ''
        expected-output: '2.4359'
        comparison-method: contains
        timeout: 5
        max-score: 500
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        E1-1_RESULTS: "${{steps.e1-1.outputs.result}}"
        E1-2_RESULTS: "${{steps.e1-2.outputs.result}}"
        E2-1_RESULTS: "${{steps.e2-1.outputs.result}}"
        E2-2A_RESULTS: "${{steps.e2-2a.outputs.result}}"
        E2-2B_RESULTS: "${{steps.e2-2b.outputs.result}}"
      with:
        runners: e1-1,e1-2,e2-1,e2-2a,e2-2b
